#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Phase 16 - Generate the experiment configuration matrix.

Every experiment is defined by a YAML file so that a run can be reproduced from
the file alone. Configs are generated rather than hand-written: the component
ablation, the data-budget sweep and the scale-transfer runs share almost all
their settings, and generating them guarantees that the shared settings really
are identical instead of merely looking identical.

Naming follows the specification:
    qwen06_zero.yaml
    qwen06_full_1h.yaml
    qwen06_textlora_5h.yaml
    qwen06_dualpeft_20h_aug.yaml

Writes configs/ plus configs/MATRIX.md listing every planned run.
"""
from __future__ import annotations

import argparse
import sys
from collections import OrderedDict
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT / "src"))

from models.components import ARMS  # noqa: E402

ARM_SHORT = OrderedDict([
    ("A0_zero_shot", "zero"),
    ("A1_full_sft", "full"),
    ("A2_audio_lora", "audiolora"),
    ("A3_projection_only", "proj"),
    ("A4_text_lora", "textlora"),
    ("A5_audio_lora_proj", "audiolora_proj"),
    ("A6_text_lora_proj", "textlora_proj"),
    ("A7_dualpeft", "dualpeft"),
])

MODELS = {
    "qwen06": "models/Qwen3-ASR-0.6B",
    "qwen17": "models/Qwen3-ASR-1.7B",
}

BUDGETS = ["1h", "5h", "10h", "20h"]

# Learning rates differ by arm because full fine-tuning and LoRA do not tolerate
# the same step size. These are the standard defaults for each family; the same
# value is used across every budget so budget is the only variable in Phase 12.
LR_BY_ARM = {
    "A1_full_sft": 2e-5,      # the rate used in the official SFT example
    "A3_projection_only": 1e-4,
    "_lora_default": 1e-4,
}


def learning_rate(arm):
    return LR_BY_ARM.get(arm, LR_BY_ARM["_lora_default"])


def dump_yaml(cfg, path):
    """Minimal YAML writer - no third-party dependency in the config generator."""
    lines = ["# Auto-generated by scripts/make_configs.py - edit the generator,",
             "# not this file, so the matrix stays internally consistent.", ""]
    for key, value in cfg.items():
        if isinstance(value, dict):
            lines.append("%s:" % key)
            for sub_key, sub_value in value.items():
                lines.append("  %s: %s" % (sub_key, _scalar(sub_value)))
        elif isinstance(value, list):
            lines.append("%s:" % key)
            for item in value:
                lines.append("  - %s" % _scalar(item))
        else:
            lines.append("%s: %s" % (key, _scalar(value)))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _scalar(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return '"%s"' % value
    if isinstance(value, float):
        # YAML 1.1 only recognises scientific notation when the mantissa has a
        # decimal point: "2e-05" parses as a *string*, not a number. That went
        # unnoticed because str(1e-4) is "0.0001" (fine) while str(2e-5) is
        # "2e-05" (broken), so only the full-SFT learning rate was affected and
        # it failed at TrainingArguments with a float/str comparison error.
        text = repr(value)
        if "e" in text and "." not in text.split("e")[0]:
            mantissa, exponent = text.split("e")
            text = "%s.0e%s" % (mantissa, exponent)
        return text
    return str(value)


def build_config(model_key, arm, budget=None, augmented=False, seed=42,
                 replay=False):
    """One resolved experiment configuration."""
    model_path = MODELS[model_key]
    is_zero = arm == "A0_zero_shot"

    if is_zero:
        train_manifest = None
    elif augmented:
        train_manifest = "data/manifests/train_%s_aug.jsonl" % budget
    else:
        train_manifest = "data/manifests/train_%s.jsonl" % budget
    if replay:
        train_manifest = "data/manifests/train_%s_replay.jsonl" % budget

    cfg = OrderedDict()
    cfg["experiment_name"] = config_name(model_key, arm, budget, augmented,
                                         seed, replay).replace(".yaml", "")
    cfg["arm"] = arm
    cfg["model_key"] = model_key
    cfg["model_path"] = model_path
    cfg["seed"] = seed
    cfg["dtype"] = "bfloat16"
    cfg["device"] = "cuda:0"

    cfg["train_manifest"] = train_manifest
    cfg["dev_manifest"] = "data/manifests/dev_synthetic.jsonl"
    cfg["data_budget"] = budget
    cfg["augmented"] = augmented
    cfg["general_replay"] = replay

    cfg["test_manifests"] = [
        "data/manifests/test_synthetic.jsonl",
        "data/manifests/test_cross_tts.jsonl",
        "data/manifests/test_aishell1.jsonl",
    ]

    cfg["lora"] = OrderedDict([("r", 16), ("alpha", 32), ("dropout", 0.05)])
    cfg["epochs"] = 3 if budget == "1h" else 2 if budget == "5h" else 1
    cfg["lr"] = learning_rate(arm)
    cfg["batch_size"] = 8
    cfg["grad_acc"] = 4
    cfg["warmup_ratio"] = 0.03
    cfg["scheduler"] = "cosine"
    cfg["gradient_checkpointing"] = arm == "A1_full_sft"
    cfg["save_steps"] = 200
    cfg["save_total_limit"] = 2
    cfg["logging_steps"] = 10
    cfg["num_workers"] = 4
    cfg["prompt"] = ""

    cfg["eval_language"] = "Chinese"
    cfg["eval_context"] = ""
    cfg["lexicon"] = "data/medical_lexicon.json"
    cfg["output_dir"] = "experiments/%s" % cfg["experiment_name"]
    return cfg


def config_name(model_key, arm, budget, augmented, seed, replay):
    parts = [model_key, ARM_SHORT[arm]]
    if budget:
        parts.append(budget)
    if augmented:
        parts.append("aug")
    if replay:
        parts.append("replay")
    if seed != 42:
        parts.append("seed%d" % seed)
    return "_".join(parts) + ".yaml"


def main():
    ap = argparse.ArgumentParser(description="Generate experiment configs.")
    ap.add_argument("--outdir", default=str(_ROOT / "configs"))
    args = ap.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    planned = []

    def add(model_key, arm, budget=None, augmented=False, seed=42, replay=False,
            phase="", note=""):
        cfg = build_config(model_key, arm, budget, augmented, seed, replay)
        name = config_name(model_key, arm, budget, augmented, seed, replay)
        dump_yaml(cfg, outdir / name)
        planned.append({"config": name, "phase": phase, "model": model_key,
                        "arm": arm, "budget": budget or "-",
                        "augmented": augmented, "replay": replay,
                        "seed": seed, "note": note})

    # Phase 8 - zero shot
    add("qwen06", "A0_zero_shot", phase="8", note="baseline, no training")
    add("qwen17", "A0_zero_shot", phase="15", note="scale reference")

    # Phase 10 - component ablation at the full 20h budget
    for arm in ARMS:
        if arm == "A0_zero_shot":
            continue
        add("qwen06", arm, "20h", phase="10", note="component ablation")

    # Phase 12 - data budget for the three arms of interest.
    # The 20h cells are the component-ablation runs above and are not repeated.
    for arm in ("A1_full_sft", "A4_text_lora", "A7_dualpeft"):
        for budget in BUDGETS:
            if budget == "20h":
                continue
            add("qwen06", arm, budget, phase="12", note="data budget")

    # Phase 13 - robustness: augmented vs not, same arm and budget
    add("qwen06", "A7_dualpeft", "20h", augmented=True, phase="13",
        note="with augmentation; compare against qwen06_dualpeft_20h")

    # Phase 14 - catastrophic forgetting: general-domain replay
    add("qwen06", "A7_dualpeft", "20h", replay=True, phase="14",
        note="90% hospital + 10% general Mandarin replay")

    # Phase 15 - scale transfer, deliberately not the full grid
    add("qwen17", "A7_dualpeft", "20h", phase="15", note="scale transfer")
    add("qwen17", "A1_full_sft", "20h", phase="15", note="optional, compute permitting")

    # Phase 17 - extra seeds only for the critical low-resource comparisons
    for seed in (123, 2026):
        for arm in ("A4_text_lora", "A7_dualpeft"):
            add("qwen06", arm, "1h", seed=seed, phase="17",
                note="seed variance at the smallest budget")

    lines = ["# Experiment matrix", "",
             "Auto-generated by `scripts/make_configs.py`. "
             "%d configurations." % len(planned), "",
             "| Config | Phase | Model | Arm | Budget | Aug | Replay | Seed | Note |",
             "|---|---|---|---|---|---|---|---|---|"]
    for item in planned:
        lines.append("| `%s` | %s | %s | %s | %s | %s | %s | %d | %s |" % (
            item["config"], item["phase"], item["model"], item["arm"],
            item["budget"], "yes" if item["augmented"] else "",
            "yes" if item["replay"] else "", item["seed"], item["note"]))
    lines += ["", "Every run must produce: `config.yaml`, `command.txt`, "
                  "`environment.txt`, `train.log`, `metrics.json`, "
                  "`predictions.jsonl`, `trainable_parameters.txt`, "
                  "`checkpoints/`."]
    (outdir / "MATRIX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("wrote %d configs to %s" % (len(planned), outdir))
    by_phase = {}
    for item in planned:
        by_phase.setdefault(item["phase"], 0)
        by_phase[item["phase"]] += 1
    for phase in sorted(by_phase, key=lambda p: int(p)):
        print("  phase %-3s %d runs" % (phase, by_phase[phase]))
    print("wrote %s" % (outdir / "MATRIX.md"))


if __name__ == "__main__":
    main()
